name: muward_b2b
description: "B2B App"

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8         # iOS style icons
  google_fonts: ^6.2.1           # Google Fonts package for custom fonts
  flutter_localizations:         # Built-in localization support
    sdk: flutter
  intl: ^0.19.0                 # Internationalization for date, number formatting, etc.
  flutter_native_splash: ^2.4.4
  country_picker: ^2.0.27
  permission_handler: ^11.4.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  provider: ^6.1.2
  geocoding: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  algoliasearch: ^1.30.2


# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0          # Recommended lints for better coding practices

# Flutter-specific configuration
flutter:
  generate: true
  uses-material-design: true     # Use Material Icons

  # Define assets for localization and other resources
  assets:
    - assets/images/
    - assets/config.json
    - assets/animations/

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
#  adaptive_icon_background: "#23AA49"
#  adaptive_icon_foreground: "assets/images/muward.png"
#  background_color_ios: "#23AA49"
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#6061FB"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
#    color: "#23AA49"
    image: assets/images/logo.png
    icon_background_color: "#6061FB"
